# Spring Application Name
spring.application.name=ledger-engine

server.port=8081
# =========================================================================
# PostgreSQL Database Settings
# =========================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=ledger_app
spring.datasource.password=${DB_PASSWORD:1995}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20

# =========================================================================
# JPA / Hibernate DDL & SQL Settings
# =========================================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================================================================
# Redis Configuration (Idempotency Guard)
# =========================================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# =========================================================================
# Actuator (Health Checks & Monitoring)
# =========================================================================
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

# =========================================================================
# RabbitMQ Configuration (Asynchronous Outbox Events)
# =========================================================================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}